# Alacritty configuration for terminals overlayed by tmux sessions.

# --------

# Visual bell animation.

[bell]
animation = "EaseOutQuint"
color = "#d7d7d7"
duration = 5

# --------

# Colors matching the rxvt-unicode default.

[colors.primary]
background = "#121212"
foreground = "#d7d7d7"

[colors.bright]
black = "#404040"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#000000"
blue = "#0000cd"
cyan = "#00cdcd"
green = "#00cd00"
magenta = "#cd00cd"
red = "#cd0000"
white = "#faebd7"
yellow = "#cdcd00"

# --------

# Set the TERM variable to 'alacritty'. 'alacritty is required
# for all feature but might not be available on all systems.
# One example is FreeBSD bevor 15.0.

[env]
TERM = "alacritty"

# --------

# Fonts.

[font]
size = 11.0

[font.normal]
family = "Kiwi Mono"
style = "Regular"

# --------

# Hide the cursor when typing.

[mouse]
hide_when_typing = true

# --------

# Disable the back buffer. tmux buffers for us.

[scrolling]
history = 0

# --------

# Always start tmux in new terminals.

[terminal.shell]
program = "/usr/opt/tmux-3d2b26d/bin/tmux"
args = ["new"]

# --------

# Light window decorations and a somehwat useable default 
# window size.

[window]
decorations_theme_variant = "Light"
dynamic_padding = true

[window.dimensions]
columns = 79
lines = 24
